### ISSUE TITLE
Port GitHub config to Terraform and remove it from govuk-saas-config.

### ISSUE THREAD

**Issue by sengi** [alphagov/govuk-saas-config#144]
There's a [GitHub Terraform provider](https://registry.terraform.io/providers/integrations/github/latest/docs). Switching to it and removing the config from govuk-saas-config would reduce toil and give us continuous deployment, nice diffs, drift detection etc. etc.

**Comment by ChrisBAshton** [comment]
Trello card to get this started: https://trello.com/c/tbQjgkwR/3249-automate-granting-team-access-to-govuk-tagged-repos-3
